Auto-Download-Placeholders: false
#Here you can combine multiple number placeholders into one!
#Operator precedence is taken into account, so these are the same:
#5 + (3 * %player_health%)
#5 + 3 * %player_health%
#And multiplication operators can usually be left out:
#5 + 3%player_health%
Formulas:
  #Shows what you can do, though it's completely pointless:
  #square(x) is a shortcut for (x * x)
  #mod is modulus. 128 mod 100 = 28, 7 mod 4 = 3
  overkill: '101(((4(5 + 3%player_food_level%) / square(2)) - 5) / 3) mod 100'
  useless:
    #sqrt(x) is the square root of x, so sqrt(4) gives 2 and sqrt(16) gives 4
    value: 'sqrt(%player_health% * %player_health%)'
    #You can specify format per-formula, or (see the bottom) use the global format
    #A documentation on this:
    #https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html
    format: '#.##' #Number rounded to 2 decimals
  reversed-food: '-%player_food_level% + 20'
  server-sum: '%bungeecord_server1% + %bungeecord_server2%'

#The formula locale to use (default, even when not specified, is english)
#This can make, for example:
#100,000.123 in english
#100.000,123 in german
#100 000,123 in french

#Formula-Locale: en_EN
