name: AnimationLib
version: 1.6.6
main: me.megamichiel.animationlib.bukkit.AnimLibPlugin
author: megamichiel
load: STARTUP
commands:
  animationlib:
    usage: /<command> reload
    permission: animationlib.reload
    description: Plugin command
    aliases: animlib
