name: AnimationLib
version: 1.5.2
main: me.megamichiel.animationlib.bukkit.AnimLibPlugin
author: megamichiel
commands:
  animationlib:
    usage: /<command> reload
    permission: animationlib.reload
    description: Plugin command
    aliases: animlib
